{{- $cloudRecords := index .Values.records .Values.global.cloudProvider | default dict -}}
{{- $records := index $cloudRecords .Values.global.environment | default list -}}
{{- if $records }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ include "keycloak-dns.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "keycloak-dns.labels" . | nindent 4 }}
spec:
  endpoints:
    {{- range $records }}
    - dnsName: {{ .dnsName | quote }}
      recordType: {{ .recordType | quote }}
      targets:
        {{- range .targets }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
{{- end }}
