apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: platform
    environment: {{ .Values.global.environment | quote }}
spec:
  instances: {{ ternary 1 .Values.cluster.instances (eq .Values.global.environment "dev") }}
  imageName: {{ .Values.cluster.imageName | quote }}
  enableSuperuserAccess: false

  storage:
    size: {{ .Values.cluster.size | quote }}
    storageClass: {{ index .Values.global.storageClass .Values.global.cloudProvider | quote }}

  resources:
{{- if eq .Values.global.environment "dev" }}
{{ toYaml .Values.cluster.devResources | indent 4 }}
{{- else }}
{{ toYaml .Values.cluster.resources | indent 4 }}
{{- end }}

  monitoring:
    enablePodMonitor: true

  bootstrap:
    initdb:
      database: {{ .Values.cluster.database | quote }}
      owner: {{ .Values.cluster.owner | quote }}
      secret:
        name: {{ .Values.cluster.ownerSecret | quote }}
      postInitSQL:
        {{- range .Values.cluster.databases }}
        - CREATE ROLE {{ .owner }};
        - CREATE DATABASE {{ .name }} OWNER {{ .owner }};
        {{- end }}

  managed:
    roles:
      {{- range .Values.cluster.roles }}
      - name: {{ .name | quote }}
        ensure: present
        login: true
        passwordSecret:
          name: {{ .passwordSecret | quote }}
      {{- end }}
