controller:
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  admissionWebhooks:
    certManager:
      enabled: true
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  service:
    externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
  allowSnippetAnnotations: false
  config:
    enable-real-ip: "true"
    proxy-body-size: 20m
    ssl-protocols: TLSv1.2 TLSv1.3
    ssl-ciphers: HIGH:!aNULL:!MD5
    hsts: "true"
    hsts-max-age: "31536000"
    hsts-include-subdomains: "true"
    keep-alive: "75"
    keep-alive-requests: "100"
    upstream-keepalive-connections: "200"
    upstream-keepalive-timeout: "60"
    use-forwarded-headers: "true"
  resources:
    requests:
      cpu: 150m
      memory: 200Mi
    limits:
      cpu: 400m
      memory: 400Mi
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - ingress-nginx
            topologyKey: kubernetes.io/hostname
