apiVersion: monitoring.coreos.com/v1beta1
kind: AlertmanagerConfig
metadata:
  name: platform-email
  namespace: monitoring
  labels:
    alertmanagerConfig: platform
    app.kubernetes.io/part-of: monitoring
spec:
  route:
    groupBy:
      - alertname
      - cluster
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    receiver: platform-email
  receivers:
    - name: platform-email
      emailConfigs:
        - to: alertmanager@monitoring.local
          from: alertmanager@monitoring.local
          smarthost: smtp.gmail.com:587
          authUsername: alertmanager@monitoring.local
          authPassword:
            name: alertmanager-smtp
            key: SMTP_PASSWORD
          requireTLS: true
